%%% This output was generated by embedproblem, version 1.7.7 (library version 1.7).
%%% Generated on Tue Feb 21 16:25:50 CET 2023
%%% using '$$dhol' embedding, version 1.0.
%%% Logic specification used:
%%% tff(dhol, logic, ($$dhol) == ([])).

thf(bool_rel, definition, (bool_rel = (^ [X:$o]: ($true)))).
thf(obj_type, type, obj: $tType).
thf(obj_rel, type, obj_rel: (obj > (obj > $o))).
thf(obj_rel_sym, axiom, (! [RX:obj,RY:obj]: ((obj_rel(RX,RY) = obj_rel(RY,RX))))).
thf(obj_rel_trans, axiom, (! [RX:obj,RY:obj,RZ:obj]: ((obj_rel(RX,RY) => (obj_rel(RY,RZ) => obj_rel(RX,RZ)))))).
thf(obj_rel_reduce, axiom, (! [RX:obj,RY:obj]: ((((RX = RY) & obj_rel(RX,RX)) = obj_rel(RX,RY))))).
thf(mor_type, type, mor: $tType).
thf(mor_rel, type, mor_rel: (obj > (obj > (mor > (mor > $o))))).
thf(mor_rel_sym, axiom, (! [X:obj,Y:obj]: ((! [RX:mor,RY:mor]: ((mor_rel(X,Y,RX,RY) = mor_rel(X,Y,RY,RX))))))).
thf(mor_rel_trans, axiom, (! [X:obj,Y:obj]: ((! [RX:mor,RY:mor,RZ:mor]: ((mor_rel(X,Y,RX,RY) => (mor_rel(X,Y,RY,RZ) => mor_rel(X,Y,RX,RZ)))))))).
thf(mor_rel_reduce, axiom, (! [X:obj,Y:obj]: ((! [RX:mor,RY:mor]: ((((RX = RY) & mor_rel(X,Y,RX,RX)) = mor_rel(X,Y,RX,RY))))))).
thf(id_type, type, id: (obj > mor)).
thf(id_tp_ax, axiom, (! [X:obj,X_prime:obj]: ((obj_rel(X,X_prime) => mor_rel(X,X,id(X),id(X)))))).
thf(comp_type, type, comp: (obj > (obj > (obj > (mor > (mor > mor)))))).
thf(comp_tp_ax, axiom, (! [X:obj,X_prime:obj]: ((obj_rel(X,X_prime) => (! [Y:obj,Y_prime:obj]: ((obj_rel(Y,Y_prime) => (! [Z:obj,Z_prime:obj]: ((obj_rel(Z,Z_prime) => (! [F:mor,F_prime:mor]: ((mor_rel(X,Y,F,F_prime) => (! [G:mor,G_prime:mor]: ((mor_rel(Y,Z,G,G_prime) => mor_rel(X,Z,comp(X,Y,Z,F,G),comp(X,Y,Z,F,G)))))))))))))))))).
thf(ax1, axiom, (! [X:obj,Y:obj,M:mor]: ((obj_rel(X,X) => (obj_rel(Y,Y) => (mor_rel(X,Y,M,M) => mor_rel(X,Y,comp(X,X,Y,id(X),M),M))))))).
thf(ax2, axiom, (! [X:obj,Y:obj,M:mor]: ((obj_rel(X,X) => (obj_rel(Y,Y) => (mor_rel(X,Y,M,M) => mor_rel(X,Y,comp(X,Y,Y,M,id(Y)),M))))))).
thf(ax3, axiom, (! [X:obj,Y:obj,Z:obj,A:obj,F:mor,G:mor,H:mor]: ((obj_rel(X,X) => (obj_rel(Y,Y) => (obj_rel(Z,Z) => (obj_rel(A,A) => (mor_rel(X,Y,F,F) => (mor_rel(Y,Z,G,G) => (mor_rel(Z,A,H,H) => mor_rel(X,A,comp(X,Y,A,F,comp(Y,Z,A,G,H)),comp(X,Z,A,comp(X,Y,Z,F,G),H)))))))))))).
thf(conj1, conjecture, (! [X:obj,Y:obj]: ((obj_rel(X,X) => (obj_rel(Y,Y) => (obj_rel(X,Y) => mor_rel(X,X,id(X),id(Y)))))))).
